# Generated by Django 6.0.5 on 2026-05-16 02:20

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import test_razonamiento.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('title', models.CharField(max_length=200, verbose_name='título interno')),
                ('stimulus_image', models.ImageField(upload_to=test_razonamiento.models.question_media_path, verbose_name='imagen estímulo')),
                ('option_1_image', models.ImageField(upload_to=test_razonamiento.models.question_media_path, verbose_name='opción 1')),
                ('option_2_image', models.ImageField(upload_to=test_razonamiento.models.question_media_path, verbose_name='opción 2')),
                ('option_3_image', models.ImageField(upload_to=test_razonamiento.models.question_media_path, verbose_name='opción 3')),
                ('option_4_image', models.ImageField(upload_to=test_razonamiento.models.question_media_path, verbose_name='opción 4')),
                ('option_5_image', models.ImageField(upload_to=test_razonamiento.models.question_media_path, verbose_name='opción 5')),
                ('option_6_image', models.ImageField(upload_to=test_razonamiento.models.question_media_path, verbose_name='opción 6')),
                ('correct_option', models.PositiveSmallIntegerField(help_text='Número de la opción correcta (1 a 6).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='opción correcta')),
                ('is_active', models.BooleanField(default=True, verbose_name='activa')),
            ],
            options={
                'verbose_name': 'pregunta',
                'verbose_name_plural': 'preguntas',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='identificador único')),
                ('role', models.CharField(choices=[('student', 'Estudiante'), ('teacher', 'Docente')], db_index=True, default='student', max_length=10, verbose_name='rol')),
                ('groups', models.ManyToManyField(blank=True, related_name='custom_user_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='custom_user_permissions', to='auth.permission')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('description', models.TextField(blank=True, verbose_name='instrucciones')),
                ('seconds_per_question', models.PositiveIntegerField(default=60, help_text='Tiempo límite individual para cada pregunta.', verbose_name='segundos por pregunta')),
                ('num_questions', models.PositiveSmallIntegerField(default=10, help_text='Cantidad de preguntas que se seleccionarán para el test.', verbose_name='número de preguntas (N)')),
                ('is_active', models.BooleanField(default=False, verbose_name='activo')),
                ('created_by', models.ForeignKey(limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'test',
                'verbose_name_plural': 'tests',
            },
        ),
        migrations.CreateModel(
            name='TestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('status', models.CharField(choices=[('in_progress', 'En curso'), ('finished', 'Finalizado')], default='in_progress', max_length=15, verbose_name='estado')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='fecha inicio')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='fecha fin')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='test_razonamiento.test')),
            ],
            options={
                'verbose_name': 'intento de test',
                'verbose_name_plural': 'intentos de test',
            },
        ),
        migrations.CreateModel(
            name='StudentResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('selected_option', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='opción seleccionada')),
                ('time_taken', models.PositiveIntegerField(default=0, verbose_name='tiempo tomado (segundos)')),
                ('is_correct', models.BooleanField(default=False, verbose_name='¿es correcta?')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_razonamiento.question')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='test_razonamiento.testattempt')),
            ],
            options={
                'unique_together': {('attempt', 'question')},
            },
        ),
        migrations.CreateModel(
            name='AttemptQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(verbose_name='orden')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_razonamiento.question')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_questions', to='test_razonamiento.testattempt')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
