# Generated by Django 6.0.5 on 2026-05-16 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_razonamiento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='tests', to='test_razonamiento.question', verbose_name='preguntas asignadas'),
        ),
    ]
