# Generated by Django 6.0.5 on 2026-05-16 03:14

import test_razonamiento.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_razonamiento', '0002_test_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='option_1_image',
            field=models.ImageField(blank=True, null=True, upload_to=test_razonamiento.models.question_media_path, verbose_name='opción 1'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_2_image',
            field=models.ImageField(blank=True, null=True, upload_to=test_razonamiento.models.question_media_path, verbose_name='opción 2'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_3_image',
            field=models.ImageField(blank=True, null=True, upload_to=test_razonamiento.models.question_media_path, verbose_name='opción 3'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_4_image',
            field=models.ImageField(blank=True, null=True, upload_to=test_razonamiento.models.question_media_path, verbose_name='opción 4'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_5_image',
            field=models.ImageField(blank=True, null=True, upload_to=test_razonamiento.models.question_media_path, verbose_name='opción 5'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_6_image',
            field=models.ImageField(blank=True, null=True, upload_to=test_razonamiento.models.question_media_path, verbose_name='opción 6'),
        ),
    ]
