# Generated by Django 6.0.5 on 2026-05-16 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_razonamiento', '0003_alter_question_option_1_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='max_attempts',
            field=models.PositiveSmallIntegerField(default=1, help_text='Número de veces que un estudiante puede realizar este test.', verbose_name='máximo de intentos'),
        ),
    ]
