# Generated by Django 6.0.5 on 2026-05-16 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_razonamiento', '0004_test_max_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='attemptquestion',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='inicio de pregunta'),
        ),
    ]
