# Generated by Django 6.0.5 on 2026-05-18 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_razonamiento', '0005_attemptquestion_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='description',
            field=models.TextField(blank=True, help_text='Texto que se mostrará antes de la imagen estímulo', verbose_name='descripción'),
        ),
    ]
